#!/usr/bin/env python3
"""Execute an authorized triage-security result on the trusted runner.

The sandbox may propose an action plan, but only the runner-provided input bundle
authorizes mutations.  This module therefore treats that bundle as the authority
for both mutation permission and retry state.
"""

import copy
import hashlib
import importlib.util
import json
import os
import sys
from typing import Any


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _load_module(name: str, filename: str):
    """Load a sibling script without making its hyphenated filename importable."""
    spec = importlib.util.spec_from_file_location(name, os.path.join(_SCRIPT_DIR, filename))
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load {}".format(filename))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# Reuse the established placeholder renderer and the fail-fast Jira client.
_action_helpers = _load_module("execute_actions", "execute-actions.py")
_jira_mod = _load_module("jira_client", "jira-client.py")


class ActionError(ValueError):
    """Raised when a sandbox plan is unsafe or incompatible with trusted input."""


_REQUIRED_ACTION_FIELDS = {
    "report-only": {"type", "marker"},
    "field-edit": {"type", "marker", "issue", "fields"},
    "status-transition": {"type", "marker", "issue", "status"},
    "comment": {"type", "marker", "issue", "body_adf"},
    "link": {"type", "marker", "link_type", "inward", "outward"},
    "remediation-task": {"type", "marker", "ref", "project", "summary", "description_adf", "labels"},
    "resolve-reference": {"type", "marker", "ref", "issue"},
}


def _plugin_version() -> str:
    """Read the installed plugin version used in triage comment footers."""
    manifest = os.path.join(_SCRIPT_DIR, "..", ".claude-plugin", "plugin.json")
    with open(manifest, encoding="utf-8") as manifest_file:
        return json.load(manifest_file)["version"]


def _browse_url(issue_key: str) -> str:
    """Build a Jira browse URL for a generated issue reference."""
    base_url = os.environ.get("JIRA_SERVER_URL", "https://jira.invalid").rstrip("/")
    return "{}/browse/{}".format(base_url, issue_key)


def _validate_action(action: Any) -> None:
    """Reject malformed or unknown action objects before they can be executed."""
    if not isinstance(action, dict):
        raise ActionError("action must be an object")
    action_type = action.get("type")
    required = _REQUIRED_ACTION_FIELDS.get(action_type)
    if required is None:
        raise ActionError("unknown action type: {}".format(action_type))
    missing = sorted(required - set(action))
    if missing:
        raise ActionError("{} action is missing {}".format(action_type, ", ".join(missing)))
    if not isinstance(action["marker"], str) or not action["marker"].startswith("triage-security:"):
        raise ActionError("action marker must use the triage-security namespace")


def _append_footer(document: dict[str, Any]) -> dict[str, Any]:
    """Append the required triage-security comment footer to an ADF document."""
    if not isinstance(document, dict) or document.get("type") != "doc":
        raise ActionError("comment body_adf must be an ADF document")
    rendered = copy.deepcopy(document)
    content = rendered.setdefault("content", [])
    if not isinstance(content, list):
        raise ActionError("comment body_adf.content must be a list")
    content.extend([
        {"type": "rule"},
        {
            "type": "paragraph",
            "content": [
                {"type": "text", "text": "This comment was AI-generated by "},
                {
                    "type": "text",
                    "text": "sdlc-workflow/triage-security",
                    "marks": [{"type": "link", "attrs": {"href": "https://github.com/RHEcosystemAppEng/sdlc-plugins"}}],
                },
                {"type": "text", "text": " v{}.".format(_plugin_version())},
            ],
        },
    ])
    return rendered


def _post_adf_comment(issue_key: str, document: dict[str, Any]) -> None:
    """Post sanitized ADF through the existing Jira client's request path."""
    _jira_mod.make_request(
        "POST", "issue/{}/comment".format(issue_key),
        {"body": _jira_mod.sanitize_adf(document)},
    )


def _description_digest(document: dict[str, Any]) -> str:
    """Compute the protocol's compact ADF SHA-256 digest for a created task."""
    canonical = json.dumps(document, separators=(",", ":"))
    return "sha256-adf:{}".format(hashlib.sha256(canonical.encode("utf-8")).hexdigest())


def _post_digest(issue_key: str) -> None:
    """Digest Jira's stored remediation description before dependent actions."""
    created = _jira_mod.get_issue(issue_key)
    description = created.get("fields", {}).get("description")
    if not isinstance(description, dict):
        raise ActionError("created remediation task has no ADF description")
    _post_adf_comment(issue_key, {
        "type": "doc",
        "version": 1,
        "content": [{
            "type": "paragraph",
            "content": [{
                "type": "text",
                "text": "[sdlc-workflow] Description digest: {}".format(_description_digest(description)),
            }],
        }],
    })


def _existing_remediation(action: dict[str, Any], trusted_input: dict[str, Any]) -> dict[str, Any] | None:
    """Return a matching prior remediation task so retries reuse its reference."""
    for existing in trusted_input.get("idempotency", {}).get("existing_remediation", []):
        labels = existing.get("labels") or []
        if existing.get("summary") == action["summary"] and "ai-generated-jira" in labels and existing.get("key"):
            return existing
    return None


def _has_description_digest(existing: dict[str, Any]) -> bool:
    """Identify whether trusted remediation state records its standalone digest."""
    return "[sdlc-workflow] Description digest:" in json.dumps(existing.get("comments", []))


def _register_existing_remediation(action: dict[str, Any], registry: dict[str, dict[str, str]], trusted_input: dict[str, Any]) -> bool:
    """Register a prior remediation task and repair a digest lost during a partial run."""
    existing = _existing_remediation(action, trusted_input)
    if existing is None:
        return False
    issue_key = existing["key"]
    registry[action["ref"]] = {"key": issue_key, "url": _browse_url(issue_key)}
    if not _has_description_digest(existing):
        _post_digest(issue_key)
    return True


def _resolve_action(action: dict[str, Any], registry: dict[str, dict[str, str]]) -> dict[str, Any]:
    """Resolve placeholders in an action or raise instead of sending them to Jira."""
    try:
        return _action_helpers.resolve_refs_in_obj(action, registry)
    except KeyError as error:
        raise ActionError("unresolved action reference: {}".format(error.args[0])) from error


def _already_applied(action: dict[str, Any], trusted_input: dict[str, Any]) -> bool:
    """Check the trusted Jira snapshot for a mutation already applied on a retry."""
    issue = trusted_input.get("issue", {})
    fields = issue.get("fields", {}) if isinstance(issue, dict) else {}
    action_type = action["type"]
    if action_type == "field-edit":
        return all(fields.get(name) == value for name, value in action["fields"].items())
    if action_type == "status-transition":
        return issue.get("status") == action["status"]
    if action_type == "link":
        for link in fields.get("issuelinks", []) or []:
            if (link.get("type", {}).get("name") == action["link_type"]
                    and link.get("inwardIssue", {}).get("key") == action["inward"]
                    and link.get("outwardIssue", {}).get("key") == action["outward"]):
                return True
    return False


def _execute_action(action: dict[str, Any], registry: dict[str, dict[str, str]], trusted_input: dict[str, Any]) -> None:
    """Perform one already-authorized action and update generated references."""
    action_type = action["type"]
    if action_type == "report-only":
        return
    if action_type == "field-edit":
        _jira_mod.update_issue(action["issue"], action["fields"])
        return
    if action_type == "status-transition":
        transitions = _jira_mod.get_transitions(action["issue"])
        transition = next(
            (item for item in transitions if item.get("to", {}).get("name") == action["status"]),
            None,
        )
        if transition is None or not transition.get("id"):
            raise ActionError("no transition named {} for {}".format(action["status"], action["issue"]))
        _jira_mod.transition_issue(action["issue"], transition["id"])
        return
    if action_type == "comment":
        document = _append_footer(action["body_adf"])
        # The native sticky-comment command persists this marker as a hidden
        # comment identity, so the pre-script can safely skip it on a retry.
        _action_helpers.post_jira_comment_native(
            action["issue"],
            _action_helpers.adf_to_markdown(document),
            marker="<!-- {} -->".format(action["marker"]),
        )
        return
    if action_type == "link":
        _jira_mod.create_link(action["inward"], action["outward"], action["link_type"])
        return
    if action_type == "resolve-reference":
        registry[action["ref"]] = {"key": action["issue"], "url": _browse_url(action["issue"])}
        return
    if action_type == "remediation-task":
        if _register_existing_remediation(action, registry, trusted_input):
            return
        labels = ["ai-generated-jira", *[label for label in action["labels"] if label != "ai-generated-jira"]]
        created = _jira_mod.create_issue(
            project_key=action["project"],
            summary=action["summary"],
            issue_type="Task",
            labels=labels,
            priority=action.get("priority"),
            fix_versions=action.get("fix_versions"),
            description_adf=action["description_adf"],
        )
        issue_key = created.get("key")
        if not issue_key:
            raise ActionError("remediation task creation returned no issue key")
        registry[action["ref"]] = {"key": issue_key, "url": _browse_url(issue_key)}
        _post_digest(issue_key)
        return
    raise ActionError("unknown action type: {}".format(action_type))


def execute_plan(result: dict[str, Any], trusted_input: dict[str, Any]) -> dict[str, dict[str, str]]:
    """Execute a validated result only when the trusted input grants mutations."""
    if not isinstance(result, dict) or not isinstance(trusted_input, dict):
        raise ActionError("result and trusted input must be objects")
    mode = result.get("mode")
    actions = result.get("actions")
    if mode not in {"report-only", "mutation-authorized"} or not isinstance(actions, list):
        raise ActionError("result has an invalid mode or action list")
    authorized = trusted_input.get("authorization", {}).get("mutation_authorized") is True
    mutating = any(isinstance(action, dict) and action.get("type") != "report-only" for action in actions)
    if mode == "report-only" and mutating:
        raise ActionError("report-only mode cannot contain mutating actions")
    if mode == "mutation-authorized" and not authorized:
        raise ActionError("mutation-authorized result is not authorized by the trusted runner")
    if mode == "report-only":
        for action in actions:
            _validate_action(action)
            if action["type"] != "report-only":
                raise ActionError("report-only mode cannot contain mutating actions")
        return {}

    markers = set(trusted_input.get("idempotency", {}).get("action_markers", []))
    registry: dict[str, dict[str, str]] = {}
    for raw_action in actions:
        _validate_action(raw_action)
        if raw_action["type"] == "resolve-reference":
            _execute_action(raw_action, registry, trusted_input)
            continue
        if raw_action["marker"] in markers:
            if raw_action["type"] == "remediation-task":
                if not _register_existing_remediation(raw_action, registry, trusted_input):
                    raise ActionError("marked remediation task is absent from trusted retry state")
            continue
        action = _resolve_action(raw_action, registry)
        if _already_applied(action, trusted_input):
            continue
        _execute_action(action, registry, trusted_input)
    return registry


def main(argv: list[str] | None = None) -> int:
    """Load runner files and exit non-zero whenever action execution fails."""
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 2:
        print("Usage: {} <result-json> <trusted-input-json>".format(sys.argv[0]), file=sys.stderr)
        return 1
    try:
        with open(args[0], encoding="utf-8") as result_file:
            result = json.load(result_file)
        with open(args[1], encoding="utf-8") as input_file:
            trusted_input = json.load(input_file)
        execute_plan(result, trusted_input)
    except Exception as error:
        print("ERROR: {}".format(error), file=sys.stderr)
        return 1
    print("Triage-security actions completed successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
